import { Vehicle } from "../types";

export const dummyCars: Vehicle[] = [
  {
    id: "1",
    name: "내 차",
    maker: "현대",
    model: "아반떼",
    year: 2020,
    fuelType: "가솔린",
    distance: 15000,
    image: "https://placehold.co/100x100@3x.png",
    buyDate: "2020-02-15",
    consumables: [
      {
        id: "1",
        name: "엔진오일",
        currentKm: 8080,
        changeKm: 15000,
        status: "good",
      },
      {
        id: "2",
        name: "연료 필터",
        currentKm: 8800,
        changeKm: 60000,
        status: "warning",
      },
      {
        id: "3",
        name: "타이어",
        currentKm: 30000,
        changeKm: 80000,
        status: "warning",
      },
      {
        id: "4",
        name: "미션오일",
        currentKm: 120000,
        changeKm: 140000,
        status: "danger",
      },
      {
        id: "5",
        name: "엔진오일2",
        currentKm: 8080,
        changeKm: 15000,
        status: "danger",
      },
      {
        id: "6",
        name: "뒷 타이어",
        currentKm: 30000,
        changeKm: 80000,
        status: "good",
      },
      {
        id: "7",
        name: "엔진오일3",
        currentKm: 3080,
        changeKm: 15000,
        status: "danger",
      },
      {
        id: "8",
        name: "엔진오일4",
        currentKm: 25080,
        changeKm: 15000,
        status: "danger",
      },
      {
        id: "9",
        name: "엔진오일5",
        currentKm: 46080,
        changeKm: 15000,
        status: "danger",
      },
    ],
  },
  {
    id: "2",
    name: "회사 차",
    maker: "현대",
    model: "소나타",
    year: 2021,
    fuelType: "가솔린",
    distance: 35000,
    image: "https://placehold.co/100x100@3x.png",
    buyDate: "2021-01-20",
    consumables: [
      {
        id: "1",
        name: "엔진오일",
        currentKm: 8080,
        changeKm: 15000,
        status: "good",
      },
      {
        id: "2",
        name: "연료 필터",
        currentKm: 8800,
        changeKm: 60000,
        status: "warning",
      },
      {
        id: "3",
        name: "타이어",
        currentKm: 30000,
        changeKm: 80000,
        status: "warning",
      },
      {
        id: "4",
        name: "미션오일",
        currentKm: 120000,
        changeKm: 140000,
        status: "danger",
      },
    ],
  },
];
